Add server quick info to help debug container
Namchee/daily-watori pull request #4
Opened 2021-01-30 04:26 UTC by chez14

In this PR:
 - Add new Discord commang `!stats` to show current bound twitter user and package version info.

This hopefully will help us to show current version of installed package on the Docker realm, #3.

Relates with #2

2021-01-30 04:27 UTC, chez14 commented
@Namchee, please help me review this one ya. Do this meets your coding standard? Thanks!

2021-01-30 10:20 UTC, Namchee requested changes
I'll leave some comments here. Mostly about `let` and `const`. Follow the linter rules.

2021-01-30 10:20 UTC, Namchee commented on src/discord/commands/stats.ts
> +    let userInfo = await twitterRepository.getSelfInfo();
Should be `const`

2021-01-30 10:20 UTC, Namchee commented on src/discord/commands/stats.ts
> +    let reply = [
Also `const`

2021-01-30 10:20 UTC, Namchee commented on src/discord/commands/stats.ts
> +    return channel.send(reply.join("\n"));
I think it's better with `MessageEmbed`

[Reference](https://discordjs.guide/popular-topics/embeds.html)

2021-01-30 10:20 UTC, Namchee commented on src/repository/twitter.ts
> +      let response = await this.twitterClient.get(
`const`

2021-01-30 10:20 UTC, Namchee commented on src/repository/twitter.ts
> +      return response?.[0]?.user;
Probably use destructuring? `?` somehow made me anxious

2021-01-31 01:57 UTC, chez14 commented
Hey @Namchee,

I've updated accordingly, just quick request, can you please add the es-lint runner to `package.json`. I intended to run the eslint **check** upon PR creation, so things can get attention accordingly.

Thanks!

2021-01-31 06:19 UTC, Namchee commented
@chez14,

I've added some linter commands in the `package.json`. Please merge it first and push it back so I can merge this one :smiley:

2021-01-31 06:58 UTC, chez14 commented
Done. I'm rebasing the branch just to make sure.

2021-01-31 12:24 UTC, Namchee approved these changes

2021-01-31 12:24 UTC, merged

2021-01-31 22:40 UTC, repurika commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.1.0`](https://github.com/Namchee/daily-watori/releases/tag/v0.1.0) :rocket: